VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "hashicorp/precise32"
  config.vm.provision :shell, path: "bootstrap.sh"
  # port forwarding so when the host (my local) gets hit on 4567 it fowards the 
  # request to the apache server on the vagrant box by hitting port 80
  config.vm.network :forwarded_port, host: 4567, guest: 80
end